name: alabanza

services:
  mongo:
    image: mongo:7.0.12
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - internal
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - internal
    ports:
      - 4004:4004
    depends_on:
      - mongo 

volumes:
  mongo_data:
networks:
  internal: # can be named anything like default or internal or backend
    driver: bridge